# https://docs.sonarsource.com/sonarqube/latest/analyzing-source-code/analysis-parameters

# Source information
sonar.sourceEncoding=UTF-8
sonar.sources=ster,kai-extension
sonar.tests=tests

# Exclusions
# On n'exclut plus tests/** car on veut qu'ils soient indexés comme tests
sonar.exclusions=

# Coverage configuration
sonar.coverage.exclusions=tests/**,scripts/**

# Python
# https://docs.sonarsource.com/sonarqube/10.4/analyzing-source-code/languages/python/
# Liste explicite des versions supportées pour éviter l'interpolation non supportée
sonar.python.version=3.11, 3.12, 3.13

# Reports
# https://docs.sonarsource.com/sonarqube/latest/analyzing-source-code/test-coverage/overview
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.xunit.reportPath=pytest-report.xml
sonar.python.xunit.skipDetails=true

# JavaScript / TypeScript
# https://docs.sonarsource.com/sonarqube/latest/analyzing-source-code/test-coverage/javascript-typescript-test-coverage/
# sonar.javascript.lcov.reportPaths=coverage/lcov.info
