"""Global configuration for the semanticlint plugin (``~/.config/ster/quality.json``).

A single global config drives **all of ster's local linting** — the TUI live view *and*
the commit-time quality gate — so what you see matches what blocks your commit. Its lint
keys (``fail_on`` / ``select`` / ``ignore`` / ``quality``) are exactly semanticlint's
``onto-ci.yml`` keys; it only adds a UI-only ``features`` block. ``onto-ci.yml`` is used
solely by the GitHub-Actions CI (the ``semanticlint`` CLI reads it); :func:`write_onto_ci`
exports the shared keys there so the repo CI can be aligned to your local config in one click.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:  # semanticlint is optional — imported lazily in build_check_config
    from semanticlint.checks.base import CheckConfig

# Threshold keys the QUA checks read, with semanticlint's own defaults.
# The three ``*_languages`` lists are per-language "must be present" requirements,
# scoped to the configured languages: ``languages`` drives semanticlint's QUA003
# (concept prefLabel per language); ``class_label_languages`` /
# ``property_label_languages`` drive ster-authored rdfs:label shapes (see
# ``language_shapes.py``) — semanticlint 0.5 has no built-in check for those.
DEFAULT_THRESHOLDS: dict = {
    "min_label_coverage": 1.0,
    "min_definition_coverage": 0.5,
    "min_class_label_coverage": 1.0,
    "min_property_label_coverage": 1.0,
    "languages": ["en"],
    "class_label_languages": [],
    "property_label_languages": [],
}

# The plugin's UI features, each independently toggleable. Read-side features default
# on; "enforce" (authoring/mutating shapes.ttl — the write side) defaults off (opt-in).
DEFAULT_FEATURES: dict = {
    "icons": True,
    "detail": True,
    "quality_block": True,
    "check_on_open": True,
    "enforce": False,
}

DEFAULT_FAIL_ON = "error"


def _config_path() -> Path:
    return Path.home() / ".config" / "ster" / "quality.json"


def load_config() -> dict:
    """The plugin config, filled with defaults for any missing key."""
    data: dict = {}
    path = _config_path()
    if path.exists():
        try:
            loaded = json.loads(path.read_text())
            if isinstance(loaded, dict):
                data = loaded
        except Exception:
            pass
    return {
        "fail_on": data.get("fail_on", DEFAULT_FAIL_ON),
        "select": list(data.get("select") or []),  # same keys as onto-ci.yml (ids/prefixes)
        "ignore": list(data.get("ignore") or []),
        "quality": {**DEFAULT_THRESHOLDS, **(data.get("quality") or {})},
        "features": {**DEFAULT_FEATURES, **(data.get("features") or {})},
    }


def save_config(config: dict) -> None:
    """Persist the plugin config (best-effort), merged onto current values."""
    merged = {**load_config(), **config}
    path = _config_path()
    try:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(json.dumps(merged, indent=2))
    except Exception:
        pass


def feature_enabled(name: str) -> bool:
    """Whether UI feature *name* (icons / detail / quality_block) is on."""
    return bool(load_config()["features"].get(name, DEFAULT_FEATURES.get(name, False)))


def set_feature(name: str, value: bool) -> None:
    features = {**load_config()["features"], name: bool(value)}
    save_config({"features": features})


def build_check_config() -> CheckConfig:
    """A semanticlint ``CheckConfig`` from the global config (select / ignore / quality).
    Only call when semanticlint is installed (imports the library)."""
    from semanticlint.checks.base import CheckConfig

    cfg = load_config()
    return CheckConfig(select=cfg["select"], ignore=cfg["ignore"], quality=cfg["quality"])


def fail_on_severity():  # type: ignore[no-untyped-def]
    """The configured blocking severity as a semanticlint ``Severity`` (defaults to
    ERROR on an unknown value). Only call when semanticlint is installed."""
    from semanticlint.checks.base import Severity

    try:
        return Severity(load_config()["fail_on"])
    except ValueError:
        return Severity.ERROR


# The lint keys shared with onto-ci.yml (the UI-only ``features`` block is excluded).
_CI_KEYS = ("fail_on", "select", "ignore", "quality")


def write_onto_ci(repo_dir: Path) -> Path:
    """Export the shared lint keys to ``<repo_dir>/onto-ci.yml`` so the GitHub-Actions CI
    matches the local quality config. Returns the written path."""
    import yaml

    cfg = load_config()
    payload = {key: cfg[key] for key in _CI_KEYS if cfg.get(key)}
    path = repo_dir / "onto-ci.yml"
    header = (
        "# onto-ci.yml — generated by ster from ~/.config/ster/quality.json\n"
        "# Used by the GitHub-Actions CI (semanticlint check). Keep in sync via ster.\n"
    )
    path.write_text(header + yaml.safe_dump(payload, sort_keys=False), encoding="utf-8")
    return path
