"""SPARQL query engine for ster.

All query logic is isolated here so that the TUI, CLI commands, and future
AI-powered callers all share the same entry-points.

Extension points
────────────────
• *run_query* / *run_query_on_graph* — pass any SPARQL string, including
  one generated by an AI, and receive a uniform ``QueryResult``.
• *PRESET_QUERIES* — a registry of built-in queries; extend this list to
  add domain-specific or AI-suggested queries to the preset menu.
• *find_uri_column* — heuristic to detect which result column contains
  concept URIs so the TUI can offer tree-navigation from results.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path

import rdflib

# ── Public data types ─────────────────────────────────────────────────────────


@dataclass
class QueryResult:
    """Normalised result from any SPARQL query type."""

    columns: list[str]
    rows: list[list[str]]  # every cell is a plain string
    error: str = ""
    query_type: str = "SELECT"  # SELECT | ASK | CONSTRUCT | DESCRIBE


@dataclass
class PresetQuery:
    label: str
    description: str
    sparql: str


# ── Common SKOS/RDF prefixes included in every preset ─────────────────────────

_PREFIXES = """\
PREFIX skos:    <http://www.w3.org/2004/02/skos/core#>
PREFIX rdfs:    <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf:     <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl:     <http://www.w3.org/2002/07/owl#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX xsd:     <http://www.w3.org/2001/XMLSchema#>
"""

# ── SPARQL 1.1 keywords and built-in functions (for editor autocomplete) ──────

SPARQL_KEYWORDS: list[str] = [
    # Query forms
    "SELECT",
    "CONSTRUCT",
    "DESCRIBE",
    "ASK",
    # Clauses
    "WHERE",
    "PREFIX",
    "BASE",
    "FROM",
    "FROM NAMED",
    "GRAPH",
    "OPTIONAL",
    "UNION",
    "FILTER",
    "BIND",
    "VALUES",
    "GROUP BY",
    "HAVING",
    "ORDER BY",
    "DESC",
    "ASC",
    "LIMIT",
    "OFFSET",
    "DISTINCT",
    "REDUCED",
    "MINUS",
    "SERVICE",
    "SILENT",
    "AS",
    "IN",
    "NOT IN",
    "EXISTS",
    "NOT EXISTS",
    # Update
    "INSERT",
    "INSERT DATA",
    "DELETE",
    "DELETE DATA",
    "DELETE WHERE",
    "WITH",
    "USING",
    "USING NAMED",
    "LOAD",
    "CLEAR",
    "DROP",
    "CREATE",
    "ADD",
    "MOVE",
    "COPY",
    "NAMED",
    "ALL",
    "UNDEF",
    # Built-in functions
    "STR",
    "LANG",
    "LANGMATCHES",
    "DATATYPE",
    "BOUND",
    "IRI",
    "URI",
    "BNODE",
    "RAND",
    "ABS",
    "CEIL",
    "FLOOR",
    "ROUND",
    "CONCAT",
    "STRLEN",
    "UCASE",
    "LCASE",
    "ENCODE_FOR_URI",
    "CONTAINS",
    "STRSTARTS",
    "STRENDS",
    "STRBEFORE",
    "STRAFTER",
    "YEAR",
    "MONTH",
    "DAY",
    "HOURS",
    "MINUTES",
    "SECONDS",
    "TIMEZONE",
    "TZ",
    "NOW",
    "UUID",
    "STRUUID",
    "MD5",
    "SHA1",
    "SHA256",
    "SHA384",
    "SHA512",
    "COALESCE",
    "IF",
    "STRLANG",
    "STRDT",
    "SAMETERM",
    "ISIRI",
    "ISURI",
    "ISBLANK",
    "ISLITERAL",
    "ISNUMERIC",
    "REGEX",
    "SUBSTR",
    "REPLACE",
    # Aggregates
    "COUNT",
    "SUM",
    "MIN",
    "MAX",
    "AVG",
    "SAMPLE",
    "GROUP_CONCAT",
    "SEPARATOR",
    # Booleans / special
    "true",
    "false",
    "a",
]

# ── Built-in preset queries ───────────────────────────────────────────────────
# Extend this list to add domain-specific or AI-generated presets.

PRESET_QUERIES: list[PresetQuery] = [
    PresetQuery(
        label="All concepts",
        description="Every concept with its preferred label.",
        sparql=_PREFIXES
        + """\
SELECT ?concept ?label
WHERE {
  ?concept a skos:Concept ;
           skos:prefLabel ?label .
}
ORDER BY ?label
""",
    ),
    PresetQuery(
        label="Missing definitions",
        description="Concepts that have no skos:definition.",
        sparql=_PREFIXES
        + """\
SELECT ?concept ?label
WHERE {
  ?concept a skos:Concept ;
           skos:prefLabel ?label .
  FILTER NOT EXISTS { ?concept skos:definition ?def }
}
ORDER BY ?label
""",
    ),
    PresetQuery(
        label="Missing alt labels",
        description="Concepts that have no skos:altLabel.",
        sparql=_PREFIXES
        + """\
SELECT ?concept ?label
WHERE {
  ?concept a skos:Concept ;
           skos:prefLabel ?label .
  FILTER NOT EXISTS { ?concept skos:altLabel ?alt }
}
ORDER BY ?label
""",
    ),
    PresetQuery(
        label="Concepts per scheme",
        description="Count of concepts in each ConceptScheme.",
        sparql=_PREFIXES
        + """\
SELECT ?scheme (COUNT(?concept) AS ?count)
WHERE {
  ?concept a skos:Concept ;
           skos:inScheme ?scheme .
}
GROUP BY ?scheme
ORDER BY DESC(?count)
""",
    ),
    PresetQuery(
        label="Top concepts",
        description="Concepts directly attached to a scheme root.",
        sparql=_PREFIXES
        + """\
SELECT ?concept ?label ?scheme
WHERE {
  ?concept a skos:Concept ;
           skos:prefLabel ?label ;
           skos:topConceptOf ?scheme .
}
ORDER BY ?scheme ?label
""",
    ),
    PresetQuery(
        label="Hierarchy",
        description="Parent → child pairs via skos:narrower.",
        sparql=_PREFIXES
        + """\
SELECT ?parent ?parentLabel ?child ?childLabel
WHERE {
  ?parent skos:narrower ?child .
  ?parent skos:prefLabel ?parentLabel .
  ?child  skos:prefLabel ?childLabel .
}
ORDER BY ?parentLabel ?childLabel
""",
    ),
    PresetQuery(
        label="Alt labels",
        description="All alternative labels per concept.",
        sparql=_PREFIXES
        + """\
SELECT ?concept ?prefLabel ?altLabel
WHERE {
  ?concept a skos:Concept ;
           skos:prefLabel ?prefLabel ;
           skos:altLabel  ?altLabel .
}
ORDER BY ?prefLabel
""",
    ),
    PresetQuery(
        label="Related concepts",
        description="All skos:related pairs.",
        sparql=_PREFIXES
        + """\
SELECT ?a ?aLabel ?b ?bLabel
WHERE {
  ?a skos:related ?b .
  ?a skos:prefLabel ?aLabel .
  ?b skos:prefLabel ?bLabel .
}
ORDER BY ?aLabel
""",
    ),
    PresetQuery(
        label="Scheme metadata",
        description="Title, creator and language of each scheme.",
        sparql=_PREFIXES
        + """\
SELECT ?scheme ?title ?creator ?lang
WHERE {
  ?scheme a skos:ConceptScheme .
  OPTIONAL { ?scheme skos:prefLabel   ?title   }
  OPTIONAL { ?scheme dcterms:creator  ?creator }
  OPTIONAL { ?scheme dcterms:language ?lang    }
}
ORDER BY ?scheme
""",
    ),
    PresetQuery(
        label="Scope notes",
        description="All skos:scopeNote values.",
        sparql=_PREFIXES
        + """\
SELECT ?concept ?label ?note
WHERE {
  ?concept a skos:Concept ;
           skos:prefLabel ?label ;
           skos:scopeNote ?note .
}
ORDER BY ?label
""",
    ),
]

# ── Core query functions ──────────────────────────────────────────────────────


def load_graph(paths: list[Path]) -> rdflib.Graph:
    """Load one or more RDF files into a single merged in-memory graph."""
    g = rdflib.Graph()
    for p in paths:
        g.parse(str(p), format=_detect_format(p))
    return g


def run_query(paths: list[Path], sparql_text: str) -> QueryResult:
    """Execute *sparql_text* against the taxonomy files at *paths*.

    Primary entry-point.  AI callers should generate a SPARQL string and
    pass it here — the result shape is always a ``QueryResult``.
    """
    if not sparql_text.strip():
        return QueryResult(columns=[], rows=[], error="Empty query.")
    try:
        g = load_graph(paths)
    except Exception as exc:
        return QueryResult(columns=[], rows=[], error=f"Load error: {exc}")
    return run_query_on_graph(g, sparql_text)


def run_query_on_graph(g: rdflib.Graph, sparql_text: str) -> QueryResult:
    """Execute *sparql_text* against an already-loaded *g*.

    Separate from *run_query* so callers that maintain a cached or augmented
    graph (e.g. with a reasoner) can skip the file-load step.
    """
    try:
        result = g.query(sparql_text)
    except Exception as exc:
        return QueryResult(columns=[], rows=[], error=f"Query error: {exc}")

    qtype = _detect_query_type(sparql_text)

    if qtype == "ASK":
        return QueryResult(
            columns=["result"],
            rows=[["true" if bool(result) else "false"]],
            query_type="ASK",
        )

    if qtype in ("CONSTRUCT", "DESCRIBE"):
        g2 = getattr(result, "graph", None)
        ttl = g2.serialize(format="turtle") if g2 is not None else ""
        lines = [ln for ln in ttl.splitlines() if ln.strip()]
        return QueryResult(columns=["triple"], rows=[[ln] for ln in lines], query_type=qtype)

    # SELECT
    cols: list[str] = [str(v) for v in result.vars] if result.vars else []
    rows: list[list[str]] = []
    for row in result:
        rows.append([_fmt_value(row[i]) for i in range(len(cols))])  # type: ignore[index]
    return QueryResult(columns=cols, rows=rows, query_type="SELECT")


def find_uri_column(result: QueryResult) -> int | None:
    """Return the index of the first column whose values look like concept URIs.

    Used by the TUI to offer direct tree-navigation from a result row.
    Returns ``None`` when no URI column is detected.
    """
    if not result.rows:
        return None
    for col_idx in range(len(result.columns)):
        sample = [row[col_idx] for row in result.rows[:10] if col_idx < len(row)]
        uri_hits = sum(
            1
            for v in sample
            if v.startswith("http://") or v.startswith("https://") or v.startswith("urn:")
        )
        if uri_hits >= max(1, len(sample) // 2):
            return col_idx
    return None


def compute_col_widths(columns: list[str], rows: list[list[str]], available: int) -> list[int]:
    """Compute column display widths to fill *available* characters.

    Each column gets at least 4 characters.  Widths are proportional to the
    maximum cell length (capped at 40) so no single column dominates.
    """
    n = len(columns)
    if n == 0:
        return []
    maxes: list[int] = [max(4, len(c)) for c in columns]
    for row in rows[:100]:
        for i, val in enumerate(row):
            if i < n:
                maxes[i] = max(maxes[i], len(val))
    maxes = [min(m, 40) for m in maxes]
    sep = n - 1  # " │ " is 3 chars but we'll use 1-char sep
    total_max = sum(maxes)
    budget = max(n * 4, available - sep * 3)
    if total_max <= budget:
        return maxes
    scale = budget / total_max
    widths = [max(4, int(m * scale)) for m in maxes]
    # absorb rounding error in the last column
    diff = budget - sum(widths)
    widths[-1] = max(4, widths[-1] + diff)
    return widths


# ── Internal helpers ──────────────────────────────────────────────────────────


def _fmt_value(val: object) -> str:
    if val is None:
        return ""
    if isinstance(val, rdflib.URIRef):
        return str(val)
    if isinstance(val, rdflib.Literal):
        lang = getattr(val, "language", None)
        return f"{val}@{lang}" if lang else str(val)
    return str(val)


def _detect_format(path: Path) -> str:
    return {
        ".ttl": "turtle",
        ".n3": "n3",
        ".jsonld": "json-ld",
        ".rdf": "xml",
        ".owl": "xml",
    }.get(path.suffix.lower(), "turtle")


def _detect_query_type(sparql_text: str) -> str:
    m = re.search(r"\b(SELECT|ASK|CONSTRUCT|DESCRIBE)\b", sparql_text, re.IGNORECASE)
    return m.group(1).upper() if m else "SELECT"
