"""SPARQL query engine for ster.

All query logic is isolated here so that the TUI, CLI commands, and future
AI-powered callers all share the same entry-points.

Extension points
────────────────
• *run_query* / *run_query_on_graph* — pass any SPARQL string, including
  one generated by an AI, and receive a uniform ``QueryResult``.
• *PRESET_QUERIES* — a registry of built-in queries; extend this list to
  add domain-specific or AI-suggested queries to the preset menu.
• *find_uri_column* — heuristic to detect which result column contains
  concept URIs so the TUI can offer tree-navigation from results.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path
from typing import TYPE_CHECKING

import rdflib

if TYPE_CHECKING:
    from .model import Taxonomy

# ── Public data types ─────────────────────────────────────────────────────────


@dataclass
class QueryResult:
    """Normalised result from any SPARQL query type."""

    columns: list[str]
    rows: list[list[str]]  # every cell is a plain string
    error: str = ""
    query_type: str = "SELECT"  # SELECT | ASK | CONSTRUCT | DESCRIBE


@dataclass
class PresetQuery:
    label: str
    description: str
    sparql: str


# ── Common SKOS/RDF prefixes included in every preset ─────────────────────────

_PREFIXES = """\
PREFIX skos:    <http://www.w3.org/2004/02/skos/core#>
PREFIX rdfs:    <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf:     <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl:     <http://www.w3.org/2002/07/owl#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX xsd:     <http://www.w3.org/2001/XMLSchema#>
"""

# ── SPARQL 1.1 keywords and built-in functions (for editor autocomplete) ──────

SPARQL_KEYWORDS: list[str] = [
    # Query forms
    "SELECT",
    "CONSTRUCT",
    "DESCRIBE",
    "ASK",
    # Clauses
    "WHERE",
    "PREFIX",
    "BASE",
    "FROM",
    "FROM NAMED",
    "GRAPH",
    "OPTIONAL",
    "UNION",
    "FILTER",
    "BIND",
    "VALUES",
    "GROUP BY",
    "HAVING",
    "ORDER BY",
    "DESC",
    "ASC",
    "LIMIT",
    "OFFSET",
    "DISTINCT",
    "REDUCED",
    "MINUS",
    "SERVICE",
    "SILENT",
    "AS",
    "IN",
    "NOT IN",
    "EXISTS",
    "NOT EXISTS",
    # Update
    "INSERT",
    "INSERT DATA",
    "DELETE",
    "DELETE DATA",
    "DELETE WHERE",
    "WITH",
    "USING",
    "USING NAMED",
    "LOAD",
    "CLEAR",
    "DROP",
    "CREATE",
    "ADD",
    "MOVE",
    "COPY",
    "NAMED",
    "ALL",
    "UNDEF",
    # Built-in functions
    "STR",
    "LANG",
    "LANGMATCHES",
    "DATATYPE",
    "BOUND",
    "IRI",
    "URI",
    "BNODE",
    "RAND",
    "ABS",
    "CEIL",
    "FLOOR",
    "ROUND",
    "CONCAT",
    "STRLEN",
    "UCASE",
    "LCASE",
    "ENCODE_FOR_URI",
    "CONTAINS",
    "STRSTARTS",
    "STRENDS",
    "STRBEFORE",
    "STRAFTER",
    "YEAR",
    "MONTH",
    "DAY",
    "HOURS",
    "MINUTES",
    "SECONDS",
    "TIMEZONE",
    "TZ",
    "NOW",
    "UUID",
    "STRUUID",
    "MD5",
    "SHA1",
    "SHA256",
    "SHA384",
    "SHA512",
    "COALESCE",
    "IF",
    "STRLANG",
    "STRDT",
    "SAMETERM",
    "ISIRI",
    "ISURI",
    "ISBLANK",
    "ISLITERAL",
    "ISNUMERIC",
    "REGEX",
    "SUBSTR",
    "REPLACE",
    # Aggregates
    "COUNT",
    "SUM",
    "MIN",
    "MAX",
    "AVG",
    "SAMPLE",
    "GROUP_CONCAT",
    "SEPARATOR",
    # Booleans / special
    "true",
    "false",
    "a",
]

# ── Built-in preset queries ───────────────────────────────────────────────────
# Extend this list to add domain-specific or AI-generated presets.

PRESET_QUERIES: list[PresetQuery] = [
    PresetQuery(
        label="All concepts",
        description="Every concept with its preferred label.",
        sparql=_PREFIXES
        + """\
SELECT ?concept ?label
WHERE {
  ?concept a skos:Concept ;
           skos:prefLabel ?label .
}
ORDER BY ?label
""",
    ),
    PresetQuery(
        label="Missing definitions",
        description="Concepts that have no skos:definition.",
        sparql=_PREFIXES
        + """\
SELECT ?concept ?label
WHERE {
  ?concept a skos:Concept ;
           skos:prefLabel ?label .
  FILTER NOT EXISTS { ?concept skos:definition ?def }
}
ORDER BY ?label
""",
    ),
    PresetQuery(
        label="Missing alt labels",
        description="Concepts that have no skos:altLabel.",
        sparql=_PREFIXES
        + """\
SELECT ?concept ?label
WHERE {
  ?concept a skos:Concept ;
           skos:prefLabel ?label .
  FILTER NOT EXISTS { ?concept skos:altLabel ?alt }
}
ORDER BY ?label
""",
    ),
    PresetQuery(
        label="Concepts per scheme",
        description="Count of concepts in each ConceptScheme.",
        sparql=_PREFIXES
        + """\
SELECT ?scheme (COUNT(?concept) AS ?count)
WHERE {
  ?concept a skos:Concept ;
           skos:inScheme ?scheme .
}
GROUP BY ?scheme
ORDER BY DESC(?count)
""",
    ),
    PresetQuery(
        label="Top concepts",
        description="Concepts directly attached to a scheme root.",
        sparql=_PREFIXES
        + """\
SELECT ?concept ?label ?scheme
WHERE {
  ?concept a skos:Concept ;
           skos:prefLabel ?label ;
           skos:topConceptOf ?scheme .
}
ORDER BY ?scheme ?label
""",
    ),
    PresetQuery(
        label="Hierarchy",
        description="Parent → child pairs via skos:narrower.",
        sparql=_PREFIXES
        + """\
SELECT ?parent ?parentLabel ?child ?childLabel
WHERE {
  ?parent skos:narrower ?child .
  ?parent skos:prefLabel ?parentLabel .
  ?child  skos:prefLabel ?childLabel .
}
ORDER BY ?parentLabel ?childLabel
""",
    ),
    PresetQuery(
        label="Alt labels",
        description="All alternative labels per concept.",
        sparql=_PREFIXES
        + """\
SELECT ?concept ?prefLabel ?altLabel
WHERE {
  ?concept a skos:Concept ;
           skos:prefLabel ?prefLabel ;
           skos:altLabel  ?altLabel .
}
ORDER BY ?prefLabel
""",
    ),
    PresetQuery(
        label="Related concepts",
        description="All skos:related pairs.",
        sparql=_PREFIXES
        + """\
SELECT ?a ?aLabel ?b ?bLabel
WHERE {
  ?a skos:related ?b .
  ?a skos:prefLabel ?aLabel .
  ?b skos:prefLabel ?bLabel .
}
ORDER BY ?aLabel
""",
    ),
    PresetQuery(
        label="Scheme metadata",
        description="Title, creator and language of each scheme.",
        sparql=_PREFIXES
        + """\
SELECT ?scheme ?title ?creator ?lang
WHERE {
  ?scheme a skos:ConceptScheme .
  OPTIONAL { ?scheme skos:prefLabel   ?title   }
  OPTIONAL { ?scheme dcterms:creator  ?creator }
  OPTIONAL { ?scheme dcterms:language ?lang    }
}
ORDER BY ?scheme
""",
    ),
    PresetQuery(
        label="Scope notes",
        description="All skos:scopeNote values.",
        sparql=_PREFIXES
        + """\
SELECT ?concept ?label ?note
WHERE {
  ?concept a skos:Concept ;
           skos:prefLabel ?label ;
           skos:scopeNote ?note .
}
ORDER BY ?label
""",
    ),
]

# ── Core query functions ──────────────────────────────────────────────────────


def load_graph(paths: list[Path]) -> rdflib.Graph:
    """Load one or more RDF files into a single merged in-memory graph."""
    g = rdflib.Graph()
    for p in paths:
        g.parse(str(p), format=_detect_format(p))
    return g


# Module-level cache: (sorted paths, mtimes) → rdflib.Graph
_graph_cache: dict[tuple, rdflib.Graph] = {}

# Module-level URI completion index cache: same key → UriIndex
# UriIndex shape: {prefix: {"all": [...], "classes": [...], "individuals": [...]}}
UriIndex = dict[str, dict[str, list[str]]]
_uri_index_cache: dict[tuple, UriIndex] = {}


def _cache_key(paths: list[Path]) -> tuple:
    """Build a cache key from paths and their current modification times."""
    return tuple((str(p), p.stat().st_mtime if p.exists() else 0) for p in sorted(paths))


def load_graph_cached(paths: list[Path]) -> rdflib.Graph:
    """Return a cached graph, re-parsing only when a file has changed on disk."""
    key = _cache_key(paths)
    if key not in _graph_cache:
        _graph_cache[key] = load_graph(paths)
    return _graph_cache[key]


def build_uri_index_cached(paths: list[Path]) -> UriIndex:
    """Return a cached URI completion index, rebuilding when any file changes."""
    from .model import Taxonomy  # avoid circular at module level  # noqa: PLC0415

    key = _cache_key(paths)
    if key not in _uri_index_cache:
        # Ensure the graph is cached first (warm the rdflib engine)
        load_graph_cached(paths)
        # Build a lightweight taxonomy snapshot for the index
        tax = Taxonomy()
        for p in paths:
            try:
                from . import store as _store  # noqa: PLC0415

                loaded = _store.load(p)
                tax.owl_classes.update(loaded.owl_classes)
                tax.owl_individuals.update(loaded.owl_individuals)
                tax.concepts.update(loaded.concepts)
                tax.schemes.update(loaded.schemes)
                tax.owl_properties.update(loaded.owl_properties)
                tax.namespace_bindings.update(loaded.namespace_bindings)
            except Exception:
                pass
        _uri_index_cache[key] = build_uri_index(tax)
    return _uri_index_cache[key]


def run_query(paths: list[Path], sparql_text: str) -> QueryResult:
    """Execute *sparql_text* against the taxonomy files at *paths*.

    Primary entry-point.  AI callers should generate a SPARQL string and
    pass it here — the result shape is always a ``QueryResult``.
    """
    if not sparql_text.strip():
        return QueryResult(columns=[], rows=[], error="Empty query.")
    try:
        g = load_graph_cached(paths)
    except Exception as exc:
        return QueryResult(columns=[], rows=[], error=f"Load error: {exc}")
    return run_query_on_graph(g, sparql_text)


def run_query_on_graph(g: rdflib.Graph, sparql_text: str) -> QueryResult:
    """Execute *sparql_text* against an already-loaded *g*.

    Separate from *run_query* so callers that maintain a cached or augmented
    graph (e.g. with a reasoner) can skip the file-load step.
    """
    try:
        result = g.query(sparql_text)
    except Exception as exc:
        return QueryResult(columns=[], rows=[], error=f"Query error: {exc}")

    qtype = _detect_query_type(sparql_text)

    if qtype == "ASK":
        return QueryResult(
            columns=["result"],
            rows=[["true" if bool(result) else "false"]],
            query_type="ASK",
        )

    if qtype in ("CONSTRUCT", "DESCRIBE"):
        g2 = getattr(result, "graph", None)
        ttl = g2.serialize(format="turtle") if g2 is not None else ""
        lines = [ln for ln in ttl.splitlines() if ln.strip()]
        return QueryResult(columns=["triple"], rows=[[ln] for ln in lines], query_type=qtype)

    # SELECT
    cols: list[str] = [str(v) for v in result.vars] if result.vars else []
    rows: list[list[str]] = []
    for row in result:
        rows.append([_fmt_value(row[i]) for i in range(len(cols))])  # type: ignore[index]
    return QueryResult(columns=cols, rows=rows, query_type="SELECT")


def find_uri_column(result: QueryResult) -> int | None:
    """Return the index of the first column whose values look like concept URIs.

    Used by the TUI to offer direct tree-navigation from a result row.
    Returns ``None`` when no URI column is detected.
    """
    if not result.rows:
        return None
    for col_idx in range(len(result.columns)):
        sample = [row[col_idx] for row in result.rows[:10] if col_idx < len(row)]
        uri_hits = sum(
            1
            for v in sample
            if v.startswith("http://") or v.startswith("https://") or v.startswith("urn:")
        )
        if uri_hits >= max(1, len(sample) // 2):
            return col_idx
    return None


def compute_col_widths(columns: list[str], rows: list[list[str]], available: int) -> list[int]:
    """Compute column display widths to fill *available* characters.

    Each column gets at least 4 characters.  When all content fits within the
    available space the actual content widths are returned unchanged.  When the
    content is wider than the screen, widths are scaled down proportionally so
    no single column dominates.
    """
    n = len(columns)
    if n == 0:
        return []
    maxes: list[int] = [max(4, len(c)) for c in columns]
    for row in rows[:100]:
        for i, val in enumerate(row):
            if i < n:
                maxes[i] = max(maxes[i], len(val))
    sep = n - 1  # " │ " separators
    budget = max(n * 4, available - sep * 3)
    total_max = sum(maxes)
    if total_max <= budget:
        return maxes
    scale = budget / total_max
    widths = [max(4, int(m * scale)) for m in maxes]
    # absorb rounding error in the last column
    diff = budget - sum(widths)
    widths[-1] = max(4, widths[-1] + diff)
    return widths


# ── Editor smart-completion helpers ──────────────────────────────────────────

_STANDARD_PREFIXES: dict[str, str] = {
    "rdf": "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
    "rdfs": "http://www.w3.org/2000/01/rdf-schema#",
    "owl": "http://www.w3.org/2002/07/owl#",
    "skos": "http://www.w3.org/2004/02/skos/core#",
    "dcterms": "http://purl.org/dc/terms/",
    "xsd": "http://www.w3.org/2001/XMLSchema#",
}

_STANDARD_QNAMES: dict[str, list[str]] = {
    "rdf": [
        "List",
        "Property",
        "first",
        "nil",
        "object",
        "predicate",
        "rest",
        "subject",
        "type",
        "value",
    ],
    "rdfs": [
        "Class",
        "Literal",
        "Resource",
        "comment",
        "domain",
        "isDefinedBy",
        "label",
        "range",
        "seeAlso",
        "subClassOf",
        "subPropertyOf",
    ],
    "owl": [
        "Class",
        "DatatypeProperty",
        "FunctionalProperty",
        "Individual",
        "NamedIndividual",
        "Nothing",
        "ObjectProperty",
        "Thing",
        "disjointWith",
        "equivalentClass",
        "inverseOf",
    ],
    "skos": [
        "Collection",
        "Concept",
        "ConceptScheme",
        "altLabel",
        "broadMatch",
        "broader",
        "broaderTransitive",
        "changeNote",
        "closeMatch",
        "definition",
        "editorialNote",
        "exactMatch",
        "example",
        "hasTopConcept",
        "hiddenLabel",
        "historyNote",
        "inScheme",
        "member",
        "narrowMatch",
        "narrower",
        "narrowerTransitive",
        "note",
        "prefLabel",
        "related",
        "relatedMatch",
        "scopeNote",
        "topConceptOf",
    ],
    "dcterms": [
        "contributor",
        "coverage",
        "created",
        "creator",
        "description",
        "format",
        "identifier",
        "language",
        "modified",
        "publisher",
        "rights",
        "source",
        "subject",
        "title",
        "type",
    ],
    "xsd": [
        "anyURI",
        "boolean",
        "date",
        "dateTime",
        "decimal",
        "double",
        "float",
        "integer",
        "langString",
        "string",
    ],
}


def build_prefix_header(namespace_bindings: dict[str, str]) -> str:
    """Build a SPARQL PREFIX block from *namespace_bindings* only.

    Emits exactly the prefixes declared in the loaded TTL file, sorted
    alphabetically.  No standard prefixes are added automatically.
    """
    return (
        "\n".join(f"PREFIX {pfx}: <{uri}>" for pfx, uri in sorted(namespace_bindings.items()))
        + "\n\n"
    )


def build_qname_index(taxonomy: Taxonomy) -> dict[str, list[str]]:
    """Build a ``prefix → [local_name, ...]`` completion index.

    Includes local names extracted from every taxonomy node (classes, individuals,
    concepts, schemes, properties) plus well-known local names for all six standard
    prefixes.  Each list is deduplicated and sorted alphabetically.
    """
    ns_to_pfx: dict[str, str] = {uri: pfx for pfx, uri in taxonomy.namespace_bindings.items()}

    index: dict[str, list[str]] = {}
    seen: set[tuple[str, str]] = set()

    def _add_uri(uri: str) -> None:
        for ns, pfx in ns_to_pfx.items():
            if uri.startswith(ns):
                local = uri[len(ns) :]
                if local and (pfx, local) not in seen:
                    seen.add((pfx, local))
                    index.setdefault(pfx, []).append(local)
                return

    for uri in (
        *taxonomy.owl_classes,
        *taxonomy.owl_individuals,
        *taxonomy.concepts,
        *taxonomy.schemes,
        *taxonomy.owl_properties,
    ):
        _add_uri(uri)

    for pfx, qnames in _STANDARD_QNAMES.items():
        for local in qnames:
            if (pfx, local) not in seen:
                seen.add((pfx, local))
                index.setdefault(pfx, []).append(local)

    for pfx in index:
        index[pfx] = sorted(index[pfx])

    return index


def build_uri_index(taxonomy: Taxonomy) -> UriIndex:
    """Build a prefix → {all, classes, individuals} completion index.

    Each sub-list is sorted alphabetically.  Standard prefix well-known names
    are included under "all" and under "classes" where appropriate.
    """
    if TYPE_CHECKING:
        pass
    ns_to_pfx: dict[str, str] = {uri: pfx for pfx, uri in taxonomy.namespace_bindings.items()}

    # Collect per-bucket
    all_map: dict[str, list[str]] = {}
    cls_map: dict[str, list[str]] = {}
    ind_map: dict[str, list[str]] = {}
    seen_all: set[tuple[str, str]] = set()

    def _add(uri: str, bucket: dict[str, list[str]]) -> None:
        for ns, pfx in ns_to_pfx.items():
            if uri.startswith(ns):
                local = uri[len(ns) :]
                if local:
                    bucket.setdefault(pfx, []).append(local)
                    if (pfx, local) not in seen_all:
                        seen_all.add((pfx, local))
                        all_map.setdefault(pfx, []).append(local)
                return

    for uri in taxonomy.owl_classes:
        _add(uri, cls_map)
    for uri in taxonomy.owl_individuals:
        _add(uri, ind_map)
    for uri in (*taxonomy.concepts, *taxonomy.schemes, *taxonomy.owl_properties):
        _add(uri, all_map)

    # Standard well-known names: add owl:Class / rdfs:Class etc. to classes bucket
    _STANDARD_CLASS_LOCALS: dict[str, list[str]] = {
        "owl": ["Class", "NamedIndividual", "Thing", "Nothing"],
        "rdfs": ["Class", "Resource"],
        "rdf": ["Property"],
    }
    for pfx, qnames in _STANDARD_QNAMES.items():
        cls_locals = set(_STANDARD_CLASS_LOCALS.get(pfx, []))
        for local in qnames:
            if (pfx, local) not in seen_all:
                seen_all.add((pfx, local))
                all_map.setdefault(pfx, []).append(local)
            if local in cls_locals and local not in cls_map.get(pfx, []):
                cls_map.setdefault(pfx, []).append(local)

    idx: UriIndex = {}
    all_pfxs = set(all_map) | set(cls_map) | set(ind_map)
    for pfx in all_pfxs:
        idx[pfx] = {
            "all": sorted(set(all_map.get(pfx, []))),
            "classes": sorted(set(cls_map.get(pfx, []))),
            "individuals": sorted(set(ind_map.get(pfx, []))),
        }
    return idx


# SPARQL predicates that signal the object position expects a class URI
_CLASS_PREDICATES: frozenset[str] = frozenset(
    {
        "a",
        "rdf:type",
        "rdfs:subClassOf",
        "rdfs:domain",
        "rdfs:range",
        "owl:equivalentClass",
        "owl:disjointWith",
        "owl:unionOf",
        "owl:intersectionOf",
        "owl:complementOf",
    }
)

# Regex: last SPARQL token before the cursor (ignoring trailing whitespace)
_LAST_TOKEN_RE = re.compile(r"(\S+)\s+$")

# Regex: PREFIX name: declarations in a SPARQL buffer
_PREFIX_DECL_RE = re.compile(r"(?i)\bPREFIX\s+(\w+)\s*:")


def _sparql_context_at_cursor(buffer: str, pos: int) -> str:
    """Return ``"class"`` when the cursor is in a position expecting a class URI.

    Strips the in-progress token (e.g. ``"kai:"`` just typed) then looks at
    the immediately preceding whitespace-separated token.  Returns ``"any"``
    for all other positions.
    """
    before = buffer[:pos]
    # Remove the in-progress token (the prefix: or partial identifier being typed)
    stripped = re.sub(r"\S+$", "", before)
    m = _LAST_TOKEN_RE.search(stripped)
    if m and m.group(1) in _CLASS_PREDICATES:
        return "class"
    return "any"


def parse_buffer_prefixes(buffer: str) -> set[str]:
    """Return the set of prefix names declared with PREFIX in *buffer*."""
    return {m.group(1) for m in _PREFIX_DECL_RE.finditer(buffer)}


def qname_candidates(idx: UriIndex, prefix: str, filter_text: str, context: str) -> list[str]:
    """Return filtered, alphabetically-sorted local names for *prefix*.

    *context* is ``"class"`` or ``"any"``.  When ``"class"``, only names from
    the ``classes`` bucket are returned.  Filter is applied case-insensitively
    as a prefix match.
    """
    bucket_key = "classes" if context == "class" else "all"
    names = idx.get(prefix, {}).get(bucket_key, [])
    f = filter_text.lower()
    return [n for n in names if n.lower().startswith(f)]


def extract_query_variables(buffer: str) -> list[str]:
    """Return a sorted, deduplicated list of ``?variable`` names in *buffer*."""
    return sorted(set(re.findall(r"\?([A-Za-z_][A-Za-z0-9_]*)", buffer)))


def extract_result_uris(rows: list[list[str]]) -> set[str]:
    """Collect every URI-like value from SELECT result rows.

    Scans all columns of all rows; any cell that starts with ``http://`` or
    ``https://`` is treated as a URI.  Returns an empty set for literal-only
    or empty result sets.
    """
    uris: set[str] = set()
    for row in rows:
        for cell in row:
            if cell.startswith("http://") or cell.startswith("https://"):
                uris.add(cell)
    return uris


# ── Internal helpers ──────────────────────────────────────────────────────────


def _fmt_value(val: object) -> str:
    if val is None:
        return ""
    if isinstance(val, rdflib.URIRef):
        return str(val)
    if isinstance(val, rdflib.Literal):
        lang = getattr(val, "language", None)
        return f"{val}@{lang}" if lang else str(val)
    return str(val)


def _detect_format(path: Path) -> str:
    return {
        ".ttl": "turtle",
        ".n3": "n3",
        ".jsonld": "json-ld",
        ".rdf": "xml",
        ".owl": "xml",
    }.get(path.suffix.lower(), "turtle")


def _detect_query_type(sparql_text: str) -> str:
    m = re.search(r"\b(SELECT|ASK|CONSTRUCT|DESCRIBE)\b", sparql_text, re.IGNORECASE)
    return m.group(1).upper() if m else "SELECT"
